version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports: # ホストOSのポートとコンテナのポートをつなげる 
      - "8080:8080"
    # links:
    #   - mysql
    tty:
      true
    volumes:
      - ./src/api:/go/src/api