apiVersion: v1
kind: Service
metadata:
  name: goapi
spec:
  type: NodePort
  selector:
    app: goapi
  ports:
    - port: 8080
      targetPort: goapi-port
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
  labels:
    app: goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          image: wakabaseisei/goapi:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: goapi-port
              protocol: TCP
