apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    character-set-server = utf8mb4
    collation-server = utf8mb4_bin

    default-time-zone = SYSTEM
    log_timestamps = SYSTEM

    [mysql]
    default-character-set = utf8mb4

    [client]
    default-character-set = utf8mb4
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    character-set-server = utf8mb4
    collation-server = utf8mb4_bin

    default-time-zone = SYSTEM
    log_timestamps = SYSTEM

    [mysql]
    default-character-set = utf8mb4

    [client]
    default-character-set = utf8mb4
