name: go-ci

on: 
  push:
    branches:
      - feature/**

jobs:
  # testを通す
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - uses: actions/checkout@v2
      - name: test
        run: cd src && go test ./... -v